title: Straightforward Navigation
description: Location awareness and pedestrian navigation designed with blind travelers in mind.
url: https://straightforwardnavigation.com
baseurl: ""
markdown: kramdown
kramdown:
  input: GFM
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
